name: Publish Python ðŸ distributions ðŸ“¦ to PyPI and TestPyPI

on: push

jobs:
  build-n-publish:
    name: Build and publish Python ðŸ distributions ðŸ“¦ to PyPI and TestPyPI
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [ '3.5', '3.6', '3.7', '3.8' ]

    steps:
    - uses: actions/checkout@master
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64

    - name: Install pipenv
      run: >-
        pip install pipenv

    - name: Install dependencies
      run: >-
        pipenv install -d

    - name: Run tests
      run: >-
        pipenv run tox

    - name: Build a binary wheel and a source tarball
      run: >-
        pipenv run python setup.py sdist bdist_wheel

    - name: Publish distribution ðŸ“¦ to Test PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
        TWINE_REPOSITORY_URL: https://test.pypi.org/legacy/
      run: >-
        TWINE_USERNAME="$TWINE_USERNAME" \
        TWINE_PASSWORD="$TWINE_PASSWORD" \
        TWINE_REPOSITORY_URL="$TWINE_REPOSITORY_URL" \
        pipenv run twine upload dist/*

    - name: Publish distribution ðŸ“¦ to PyPI
      if: startsWith(github.ref, 'refs/tags')
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        TWINE_REPOSITORY_URL: https://upload.pypi.org/legacy/
      run: >-
        TWINE_USERNAME="$TWINE_USERNAME" \
        TWINE_PASSWORD="$TWINE_PASSWORD" \
        TWINE_REPOSITORY_URL="$TWINE_REPOSITORY_URL" \
        pipenv run twine upload dist/*
